// DeviceIDView.swift
//
// This code is provided under the MIT License.
//
// Please visit www.count.ly for more information.

import SwiftUI

struct DeviceIDView: View {
    private var deviceID: DeviceIDAPI { AppContext.active.deviceID }

    @State private var newID = "new-device-id"

    var body: some View {
        FeatureList {
            Section("Current") {
                ActionButton("Print Device ID and Type") {
                    AppLog.shared.log("id: \(deviceID.current ?? "none"), type: \(String(describing: deviceID.type)), temporary: \(deviceID.isTemporaryIDMode)")
                }
            }

            Section {
                LabeledField("Device ID", text: $newID, placeholder: "new-device-id")
            } header: {
                Text("The ID these buttons set")
            }

            Section {
                ActionButton("Set ID") { deviceID.setID(newID) }
            } header: {
                Text("Set")
            } footer: {
                FootnoteText("Merges when the current ID was generated by the SDK, because that is the same person identifying themselves. Does not merge when the host application supplied the previous ID, because a second supplied ID is a different user.")
            }

            Section("Change explicitly") {
                ActionButton("Change with Server Merge") { deviceID.changeWithMerge(newID) }
                ActionButton("Change without Merge") { deviceID.changeWithoutMerge(newID) }
            }

            Section {
                ActionButton("Enable Temporary ID Mode") { deviceID.enableTemporaryIDMode() }
                ActionButton("Leave Temporary ID Mode") { deviceID.changeWithoutMerge(newID) }
            } header: {
                Text("Temporary mode")
            } footer: {
                FootnoteText("Nothing is sent while temporary mode is on. Everything recorded meanwhile is rewritten to the real ID and released when one is set.")
            }
        }
    }
}
