// DeviceIDView.swift
//
// This code is provided under the MIT License.
//
// Please visit www.count.ly for more information.

import SwiftUI

struct DeviceIDView: View {
    private var deviceID: DeviceIDAPI { Countly.shared.deviceID }

    var body: some View {
        Form {
            Section("Current") {
                ActionButton("Print Device ID and Type") {
                    AppLog.shared.log("id: \(deviceID.current ?? "none"), type: \(String(describing: deviceID.type)), temporary: \(deviceID.isTemporaryIDMode)")
                }
            }

            Section {
                ActionButton("Set ID") { deviceID.setID("new-device-id") }
            } header: {
                Text("Set")
            } footer: {
                Text("Merges when the current ID was generated by the SDK, because that is the same person identifying themselves. Does not merge when the host application supplied the previous ID, because a second supplied ID is a different user.")
            }

            Section("Change explicitly") {
                ActionButton("Change with Server Merge") { deviceID.changeWithMerge("merged-device-id") }
                ActionButton("Change without Merge") { deviceID.changeWithoutMerge("fresh-device-id") }
            }

            Section {
                ActionButton("Enable Temporary ID Mode") { deviceID.enableTemporaryIDMode() }
                ActionButton("Leave Temporary ID Mode") { deviceID.changeWithoutMerge("real-device-id") }
            } header: {
                Text("Temporary mode")
            } footer: {
                Text("Nothing is sent while temporary mode is on. Everything recorded meanwhile is rewritten to the real ID and released when one is set.")
            }
        }
    }
}
